version: '3'
services:
  db:
    image: registry.centos.org/postgresql/postgresql:9.6
    container_name: stopwatch_db
    ports:
      - "5439:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db-data: